export const data = [
    "ASSESSMENT / DEVELOPMENT CENTRES",
    "HR AUDIT / DIAGNOSTICS",
    "COACHING / MENTORING FOR LEADERS",
    "VISION / MISSION / VALUE / CULTURE",
    "IMPROVING EMPLOYEE ENGAGEMENT THROUGH SURVEY AND AWARD",
    "COMPETENCY FRAMEWORK / MATRIX",
    "360 DEGREE REVIEW / FEEDBACK",
    "JOB EVALUATION",
    "IDP / SUCCESSION PLANNING FOR LEADERSHIP PIPELINE",
    "ORGANIZATION RESTRUCTURING  / JD'S",
    "BUILDING PERFORMANCE CULTURE",
    "HR HAND BOOK-POLICIES / PROCESSES",
    "GOVERNANCE FRAMEWORK",
    "EXECUTING HIRING HEAD HUNTING"

]